[package]
name = "discover"
version = "0.1.0"
authors = ["taoyu <t1997y@vip.qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
percent-encoding = "2.1"
serde_json = "1.0"